#!/usr/bin/perl -w -Ilib/

use strict;
use warnings;

use Blog::Spam::Server;




#
#  Create the server.
#
my $proxy = Blog::Spam::Server->new();


#
#  Start out server listening upon the named port.
#
$proxy->createServer( port => 8888 ) || exit(0);


#
#  Fire her up
#
$proxy->runLoop() || exit(0);

